version: "3.5"
volumes:
  postgres-data:
services:
  db:
    image: "postgres:12.3-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a1b2c3
      POSTGRES_DB: test-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
